[project]
name = "hexlet-code"
version = "0.1.0"
description = "Second project - gendiff"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["hexlet_code"] 

[project.scripts]
gendiff = "hexlet_code.scripts.gendiff:main" 