name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          make install

      - name: Run linter (ruff)
        run: make check

      - name: Run tests with coverage
        run: make test-coverage

      - name: Generate coverage report
        run: coverage xml -o coverage.xml

      - name: Upload coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=WhiteA77_python-project-50
            -Dsonar.organization=WhiteA77
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
